landingpage/urls.py
from django.urls import path
from . import views
app_name = "landingpage"
urlpatterns = [
    path('', views.index, name='index'),
]

nepscribe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('transcribe', include('transcribe.urls')),
    path('', include('landingpage.urls')),
    path('admin/', admin.site.urls),
]

transcribe/urls.py
from django.urls import path
from . import views
app_name = "transcribe"
urlpatterns = [
    path('', views.index, name='index'),
]

landingpage/models.py
from django.db import models

# Create your models here.

transcribe/models.py
from django.db import models

# Create your models here.

landingpage/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, "landingpage/index.html")

transcribe/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, "transcribe/index.html")

landingpage/templates/landingpage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nepscribe</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'landingpage/style.css' %}" />
  </head>
  <body>
    <div class="pane">
      <a class="btn btn-light" href="{% url 'transcribe:index' %}">
        Transcribe</a
      >
    </div>
  </body>
</html>

transcribe/templates/transcribe/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nepscribe</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap"
      rel="stylesheet"
    />
    <script
      src="https://kit.fontawesome.com/1a6e1f4509.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'transcribe/style.css' %}" />
  </head>
  <body>
    <nav class="nav-container navbar mb-auto">
      <span class="navbar-brand mb-0 h1">Nepscribe</span>
    </nav>
    <div class="body-container">
      <div class="container">
        <div class="form-input">
          <p class="speech-text" contenteditable="true">
            तपाई अंग्रेजी बोल्नु हुन्छ?
          </p>
        </div>
        <button type="button" class="btn">
          <i class="fa fa-microphone fa-2x"></i>
          <span class="recording"><b>REC</b></span>
        </button>
        <div class="animate">
          <p class="listening">listening</p>
          <div class="loading">
            <div class="snippet" style="margin-left: 30px">
              <div class="stage">
                <div class="dot-flashing"></div>
              </div>
            </div>
          </div>
        </div>
        <audio class="mt-3 mb-3" id="audioPlayer" controls></audio>
        <a href="#" id="downloadButton">Download</a>
      </div>
    </div>
    <script
      type="text/javascript"
      src="{% static 'transcribe/index.js' %}"
    ></script>
  </body>
</html>